controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::home
